name: web
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - flask
  - matplotlib
  - numpy
  - scipy
  - uwsgi
  - pip:
    - hyde
    - httplib2
    - google-api-python-client
    - oauth2client 
