name: web
channels:
  - gustavorabello
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - flask
  - matplotlib
  - httplib2
  - google-api-python-client
  - oauth2client 
  - numpy
  - scipy
  - uwsgi
  - pip:
    - hyde
