name: web
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - flask
  - matplotlib
  - conda-forge::google-api-python-client
  - conda-forge::oauth2client 
  - numpy
  - scipy
  - uwsgi
  - pip:
    - hyde
    - httplib2
